
__Упражнение 1 -  Numpy__
1. Пусть у двух матриц совпадает количество строк. Объедините их в одну горизонтально (объедините столбцы этих матриц)

2. Пусть дана пuтру-матрица $M$ и два массива индексов $a, b$ одинаковой длины. Постройте массив элементов $M[a[0], b[0]], M[a[1], b[1]], \ldots$ Указание: для выполнения этой операции не требуется никаких именных функций.

3. Подсчитайте след матрицы и количество ненулевых элементов на ее диагонали

4. Даны два произвольных numpy-массива одинаковой размерности $(n, m)$. Замените нулями те элементы второго массива, для которых на соответствующем месте в первом массиве находятся отрицательные числа

5. Даны две матрицы с одинаковым количеством строк и количеством столбцов $n$ и $m$ соответственно. Постройте матрицу $n \times m$ всевозможных произведений столбцов друг на друга (в смысле скалярного произведения).

In [1]:
import numpy as np

In [30]:
# 1 пункт
n = int(input()) # Строка 1 и 2
m = int(input()) # Строка 1
l = int(input()) # Строка 2 
A = np.random.randint(5, size=(n,m))
B = np.random.randint(n, size=(n,l))
C = np.concatenate((A, B), axis=1)

print(A)
print(B)
print(C)




 4
 5
 6


[[1 0 0 0 0]
 [2 2 0 0 4]
 [2 2 0 1 0]
 [2 2 1 1 1]]
[[1 3 3 0 0 3]
 [2 3 2 0 1 2]
 [2 1 1 3 0 0]
 [3 2 2 2 3 3]]
[[1 0 0 0 0 1 3 3 0 0 3]
 [2 2 0 0 4 2 3 2 0 1 2]
 [2 2 0 1 0 2 1 1 3 0 0]
 [2 2 1 1 1 3 2 2 2 3 3]]


2. Пусть дана пuтру-матрица $M$ и два массива индексов $a, b$ одинаковой длины. Постройте массив элементов $M[a[0], b[0]], M[a[1], b[1]], \ldots$ Указание: для выполнения этой операции не требуется никаких именных функций.

In [54]:
###### 2 пункт
n = int(input())
A = np.random.randint(5, size=(n,n))
a = np.arange(0,n)
b = np.arange(0,n)
print(A)
answer = A[a,b]

print("\n",answer)

 9


[[2 3 0 0 4 3 3 2 1]
 [4 1 0 0 2 4 2 1 4]
 [4 4 0 4 3 1 0 4 2]
 [0 3 3 3 0 0 1 4 1]
 [1 4 0 2 3 0 2 1 3]
 [1 2 0 0 4 3 3 2 4]
 [2 2 1 2 2 1 1 2 0]
 [3 3 3 1 3 2 3 0 0]
 [0 2 3 1 2 3 0 1 2]]

 [2 1 0 3 3 3 1 0 2]


3. Подсчитайте след матрицы и количество ненулевых элементов на ее диагонали

In [9]:
###### 3 пункт
n = int(input())
A = np.random.randint(5, size=(n,n))
a = np.arange(0,n)
b = np.arange(0,n)
print(np.trace(A))
a = A[a, b]
print(A)
print(np.count_nonzero(a))

 9


15
[[3 2 2 0 4 0 3 1 2]
 [1 0 3 3 1 3 0 1 4]
 [1 0 2 0 0 3 2 1 2]
 [3 0 0 0 0 0 0 2 3]
 [3 2 3 0 1 0 3 3 3]
 [4 4 2 1 4 2 0 1 1]
 [4 2 2 0 4 2 1 0 3]
 [1 1 0 4 0 2 3 2 0]
 [1 3 4 0 0 4 2 1 4]]
7


4. Даны два произвольных numpy-массива одинаковой размерности $(n, m)$. Замените нулями те элементы второго массива, для которых на соответствующем месте в первом массиве находятся отрицательные числа

In [50]:
n = int(input())
m = int(input())

A = 10 - np.random.randint(20, size=(n,m))
B = 10 - np.random.randint(20, size=(n,m))
print(A)
B = B * (1 - (A < 0))
print(B)

 5
 6


[[ 4 -1 10 -2 -3 -2]
 [-8  9 -6  2  1 10]
 [-6 -8 -4 -6 -1 -3]
 [-2 -8  9  6  5  9]
 [ 0  2  3  1  8 -3]]
[[-2  0 -6  0  0  0]
 [ 0 -1  0 -4  7  6]
 [ 0  0  0  0  0  0]
 [ 0  0 -6  0 -9 -6]
 [10 -1 -8 -9  5  0]]


5. Даны две матрицы с одинаковым количеством строк и количеством столбцов $n$ и $m$ соответственно. Постройте матрицу $n \times m$ всевозможных произведений столбцов друг на друга (в смысле скалярного произведения).

In [79]:
n = int(input())
m = int(input())
A = np.random.randint(4, size=(n,m))
B = np.random.randint(4, size=(n,m))
answer = np.zeros((n,m))
print(A, '\n\n', B)
for i in range(n):
    for j in range(m):
        answer[i][j] = np.dot(A[:,i], B[:,j])
print('\n',answer)

 2
 3


[[2 3 1]
 [1 2 0]] 

 [[0 3 3]
 [3 1 3]]

 [[ 3.  7.  9.]
 [ 6. 11. 15.]]
