## Домашнее задание

__Задание 1. Генератор случайных матриц.__

Реализовать генератор матриц, который должен поддерживать функции:
* Генерация абсолютно случайной матрицы $n\times m$ -
* Генерация случайной диагональной матрицы $n\times n$ -
* Генерация случайной верхнетреугольной матрицы -
* Генерация случайной нижнетреугольной матрицы-
* Генерация симметричной матрицы -
* Генерация вырожденной матрицы - 
* Генерация матрицы ступенчатого вида $n\times n$ ранга $m$
* Генерация возмущения матрицы $n\times m$, каждый элемент которой не превосходит по модулю заданный $\varepsilon$. Оценить величину нормы матрицы возмущений в зависимости от параметра $\varepsilon$ (оценить верхную границу).

Оценить численно вероятность того, что созданная матрица будет вырожденной для какого-либо случая выше.

In [54]:
import numpy as np

def matrix_generate(rows, columns, type_ = "full", eps = 0):

    A = None

    if type_ == "full":

        A = np.random.random(size=(rows, columns))

    
    elif type_ == "down_triangular":

        A = np.random.random(size=(rows, columns))

        for i in range(rows):
            for j in range(columns):
                if (i < j):
                    A[i, j] = 0

        # Для нижнетреугольной подумайте, как сделать без циклов for :) (звёздочка)

    elif type_ == "upper_triangular":

        A = np.random.random(size=(rows, columns))

        for i in range(rows):
            for j in range(columns):
                if (i > j):
                    A[i, j] = 0

        # Для нижнетреугольной подумайте, как сделать без циклов for :) (звёздочка)

    elif type_ == "symmetric":

        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"

        else:

            A = np.random.random(size=(rows, columns))

            for i in range(rows):
                for j in range(columns):
                    if (i > j):
                        A[i, j] = A[j, i]

    elif type_ == "degenerate":

        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"

        else:

            A = np.random.random(size=(rows, columns))

            for i in range(1, rows):
                for j in range(columns):
                        A[i, j] = (1+i)*A[0, j]


    elif type_ == "diagonal":

        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"

        else:

            A = np.random.random(size=(rows, columns))

            for i in range(rows):
                for j in range(columns):
                    if (i != j):
                        A[i,j] = 0

            # И эту секцую тоже перепишите без for (звёздочка). Учтите, что портить uniform распределение нельзя.

    elif type_ == "stepwise":

        A = np.random.random(size=(rows, rows))
        for i in range(rows):
            for j in range(rows):
                if (i > j):
                    A[i,j] = 0
        for m in range(rows - columns):
            for j in range(rows):
                A[rows-m-1][j] = 0
                    


    return A

In [3]:
matrix_generate(1, 3)

array([[0.10055617, 0.85013716, 0.8588409 ]])

In [6]:
matrix_generate(4, 2, type_ = "down_triangular")

array([[0.78927594, 0.        ],
       [0.00401806, 0.33667584],
       [0.4596083 , 0.92819929],
       [0.6963258 , 0.93775909]])

In [13]:
matrix_generate(4, 4, type_ = "diagonal")

array([[0.74154166, 0.        , 0.        , 0.        ],
       [0.        , 0.429191  , 0.        , 0.        ],
       [0.        , 0.        , 0.58830367, 0.        ],
       [0.        , 0.        , 0.        , 0.80183308]])

In [18]:
a = matrix_generate(4, 4, type_ = "degenerate")
np.linalg.det(a)

0.0

In [59]:

print(matrix_generate(6, 4, type_ = "stepwise"))

[[0.24129546 0.56553891 0.91920493 0.16082176 0.40749942 0.81601009]
 [0.         0.90139662 0.04577891 0.31828164 0.1230551  0.81303241]
 [0.         0.         0.22872778 0.19833349 0.65747729 0.34450375]
 [0.         0.         0.         0.25485052 0.59232852 0.68884517]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
